In [1]:
import numpy as np

In [10]:
class Neural_Network(object):
    def __init__(self):
        
  #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
  #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (2x3) weight matrix
        #from input to hidden layer
        print(self.W1)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix 
        #from hidden to output layer
        print(self.W2)

In [11]:
def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o

  

In [12]:
def sigmoid(self, s):
    # activation function
    return 1/(1+np.exp(-s))


In [13]:
def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)


In [15]:
  def backward(self, X, y, o):
    # backward propagate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error
    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error
    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights



In [16]:
def train(self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)



In [17]:
  def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")



In [18]:
def predict(self):
    print ("Predicted data based on trained weights: ")
    print ("Input (scaled): \n" + str(xPredicted))
    print ("Output: \n" + str(self.forward(xPredicted)))


In [19]:
# X = (hours studying, hours sleeping), y = score on test, xPredicted = 4 hours studying & 8 hours sleeping (input data for prediction)
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)


In [20]:
# scale units
print(X)
X = X/np.amax(X, axis=0) # maximum of X array
print(X)


[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [21]:
print(xPredicted)
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)
print(xPredicted)

[4. 8.]
[0.5 1. ]


In [22]:
y = y/100 # max test score is 100


In [23]:
NN = Neural_Network()


[[-0.27501957 -1.03469615  1.20920417]
 [-0.67887956 -0.03660003  0.23144134]]
[[-0.66438222]
 [-0.08444652]
 [ 2.28255799]]


In [26]:

for i in range(10): # trains the NN 1,000 times
    print ("# " + str(i) + "\n")
    print ("Input (scaled): \n" + str(X))
    print ("Actual Output: \n" + str(y))
    print ("Predicted Output: \n" + str(NN.forward(X)))
    print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X)))) )# mean sum squared loss
    print ("\n")
    NN.train(X, y)




# 0

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]


AttributeError: 'Neural_Network' object has no attribute 'forward'

In [25]:
NN.saveWeights()
NN.predict() 

SyntaxError: invalid non-printable character U+2003 (1317916587.py, line 2)